export const items = [
  {
    id: 1,
    imgSrc: "https://i.ibb.co/CvMbVTM/dashoard.jpg",
    technology: "HTML CSS JavaScript",
    title: "Dashboard",
    info: "Dashboard => bilimlarni mustahkamlash uchun youtube ga qarab qilingan loyiha",
    liveSrc: "https://mjb-dashboard.netlify.app",
    codeSrc: "https://github.com/JavohirShirinboyev/dashboard",
  },
  {
    id: 2,
    imgSrc: "https://i.ibb.co/DrxY0zb/earthimu.jpg",
    technology: "HTML CSS JavaScript React",
    title: "Earthimu",
    info: "Amaliyot => React (styled-component)",
    liveSrc: "https://crypt-game.netlify.app/",
    codeSrc: "https://github.com/JavohirShirinboyev/Crypt-Game",
  },
  {
    id: 3,
    imgSrc: "https://i.ibb.co/6b7Yh4s/leanding-Page.jpg",
    technology: "HTML CSS JavaScript React",
    title: "Shopping Web Site",
    info: "React => reactstrap styled-components",
    liveSrc: "https://online-shop-landing-page-javohir.netlify.app/",
    codeSrc: "https://github.com/JavohirShirinboyev/Online-shop-landing-page",
  },
  {
    id: 4,
    imgSrc: "https://i.ibb.co/DM6jS1G/weather.jpg",
    technology: "HTML CSS JavaScript React Vite2.0",
    title: "Weather",
    info: "Weather => React Vite2.0 API(openweathermap)",
    liveSrc: "https://weather-app-reactjs-javohir.netlify.app/",
    codeSrc: "https://github.com/JavohirShirinboyev/React-js-Weather-App",
  },
  {
    id: 5,
    imgSrc: "https://i.ibb.co/sm7m85K/todo.jpg",
    technology: "HTML CSS JavaScript React",
    title: "Todo App",
    info: "Todo App => used React, useReducer and filter",
    liveSrc: "https://todo-app313.netlify.app/",
    codeSrc: "https://github.com/JavohirShirinboyev/todo1",
  },
];
